version: 2.1

jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: CCA.Services.RepositoryNook
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: CCA.Services.RepositoryNook
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: CCA.Services.RepositoryNook.Tests
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            docker build -t gcr.io/repositorynookproject-263716/reponook-ui:latest .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push gcr.io/repositorynookproject-263716/reponook-ui:latest