version: 2.1
orbs:
  gcloud: circleci/gcp-cli@1.0.6
  gcr: circleci/gcp-gcr@0.0.263716

commands:
  install:
    description: "Install 'gcloud' if not already installed."
    steps:
        - gcloud/install

  init:
    description: "Intialize the 'gcloud' CLI."
    steps:
        - gcloud/initialize

jobs:
  build:
    description: "Push image to GCR"
    machine: true
    steps:
        - checkout
        - setup_remote_docker:
            docker_layer_caching: false
        - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
        - run: docker build --rm=false -t gcr.io/repositorynookproject-263716/reponook-ui:latest .
        - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
        - run: gcloud --quiet config set project repositorynookproject-263716
        - run: gcloud docker --push cr.io/repositorynookproject-263716/reponook-ui:latest
workflows:
  version: 2
  build-master:
    jobs:
        - build