version: 2.1
jobs:
  build:
    machine: true
    steps:
        - checkout
        - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
        - run: docker build --rm=false -t gcr.io/${GOOGLE_PROJECT_ID}/reponook-ui:latest .
        - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
        - run: gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
        - run: gcloud docker --push cr.io/${GOOGLE_PROJECT_ID}/reponook-ui:latest
workflowsw:
    version: 2
    build-master:
        jobs:
            - build