version: 2.1

jobs:
  build:
    description: "Build & Push image to GCR repository"
    machine: true
    steps:
        - checkout
        - run: docker build --rm=false -f ./CCA.Services.RepositoryNook/Dockerfile -t gcr.io/${GOOGLE_PROJECT_ID}/reponook-svc:latest ./CCA.Services.RepositoryNook
        - run: echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcp-key.json
        - run: docker login -u _json_key --password-stdin https://gcr.io < ${HOME}/gcp-key.json
        - run: docker push gcr.io/${GOOGLE_PROJECT_ID}/reponook-svc:latest
workflows:
  version: 2
  build-master:
    jobs:
        - build