version 2.1
jobs:
    build:
        docker:
            - image: alpine:3.7
        steps:
            - run:
                name: The First steps
                command: |
                    echo 'Hello World!'
                    echo 'This is the delivery pipeline'