version: 2.1
orbs:
  gcloud: circleci/gcp-cli@1.8.3
  gcr: circleci/gcp-gcr@0.6.1

commands:
  install:
    description: "Install 'gcloud' if not already installed."
    steps:
        - gcloud/install

  init:
    description: "Intialize the 'gcloud' CLI."
    steps:
        - gcloud/initialize

jobs:
  build:
    description: "Push image to GCR."
    machine: true
    steps:
        - run: echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcp-key.json
        - checkout
        - install
        - init
        - run: docker build --rm=false -f ./CCA.Services.RepositoryNook/Dockerfile -t gcr.io/${GOOGLE_PROJECT_ID}/reponook-ui:latest ./CCA.Services.RepositoryNook
        - run: docker push gcr.io/${GOOGLE_PROJECT_ID}/reponook-ui:latest
workflows:
  version: 2
#  install_and_configure_cli:
#    jobs:
#        - gcloud/install_and_initialize_cli:
#           context: myContext
#            executor: gcloud/default
  build-master:
    jobs:
        - build