apiVersion: apps/v1
kind: Deployment
metadata:
  name: reponook
spec:
  replicas: 2
  selector:
    matchLabels:
      run: reponook
  template:
    metadata:
      labels:
        run: reponook
    spec:
      containers:
      - name: reponook-pod
        image: docker.io/mtmazurik/repositorynook:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 80