apiVersion: v1
kind: Service
metadata:
  name: reponook
  labels: 
    run: reponook
spec:
  type: LoadBalancer
  ports:
  - port: 8192
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: reponook