apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: reponook
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: reponook
    spec:
      containers:
      - name: reponook-pod
        image: docker.io/mtmazurik/repositorynook:dev
        imagePullPolicy: Always
        ports:
          - containerPort: 80